- reformat:
    check: goimports -l -local gopkg.in/launchdarkly/gogitix.v2 {{ ._files_ }}
    format: goimports -w -local gopkg.in/launchdarkly/gogitix.v2 {{ ._files_ }}
- parallel:
    - run: dep status
    {{ if gt (len .packages) 0 }}
    - run: staticcheck {{ ._packages_ }}
    {{ end }}
    {{ if gt (len .dirs) 0 }}
    - run:
        name: go vet
        command: go tool vet -composites=false {{ ._dirs_ }}
    {{ end }}
    {{ if gt (len .packages) 0 }}
    - run:
        name: gotest compile
        description: Compiling and initializing tests (but not running them)
        command: |
          go test -run non-existent-test-name {{ ._packages_ }}
    {{ end }}
